### ISSUE TITLE
moment.js

### ISSUE THREAD

**Issue by devSoyoung** [DevLeti/web#1]
https://momentjs.com/
이 친구가 빠질 수 없지요

**Comment by DevLeti** [comment]
지금 이 이슈가 있는걸 확인했습니다... 시간표현에 관련된 유용한 라이브러리네요! 추가하겠습니다!

**Comment by devSoyoung** [comment]
얼마전에 알게 된건데 [day.js](https://day.js.org/)라구 더 용량 작은 라이브러리가 있더라고
타임존이나 다국어 지원 등등 많은 기능이 필요한게 아니라
간단한 날짜/시간 조작이 목적이라믄 요걸 한번 써보는것두..

**Comment by DevLeti** [comment]
2kb로 작은 용량이지만 필수적인 기능들이 잘 구현되어 있고 타임존같이 더 많은 기능이 필요할땐 플러그인으로 추가해서 사용할 수 있네요! 더 알아보고 정리해서 올리도록 하겠습니다~
